Examples migration for users module
microsoftgraph/msgraph-sdk-powershell pull request #1693
Opened 2022-12-16 13:15 UTC by timayabi2020

﻿

Fixes #1559

2022-12-20 16:46 UTC, peombwa requested changes
@timayabi2020, we still need to update the beta examples to use beta commands - `*-MgBeta*` instead of `*-Mg*`.

Also, can you include the script used to perform the rename in the PR. The script will act as the foundation for a v1 to v2 migration tool.

2022-12-21 17:37 UTC, timayabi2020 commented on src/Users/beta/examples/Get-MgBetaUser.md
> +Get-MgUser -All | Format-List  ID, DisplayName, Mail, UserPrincipalName
The changes inside the files have been done as per request

2022-12-21 18:09 UTC, peombwa approved these changes

2022-12-21 20:46 UTC, peombwa approved these changes

2022-12-22 04:59 UTC, merged