Add flag to send certificate chain for subject name / issuer based auth in Connect-MgGraph
microsoftgraph/msgraph-sdk-powershell pull request #2699
Opened 2024-04-24 00:20 UTC by nayanshah

﻿

Fixes #2698 

### Changes proposed in this pull request

Adds a flag `SendCertificateChain` to `Connect-MgGraph` to send entire certificate chain while requesting access token. This allows subject name / issuer based auth.

### Other links

`ClientCertificateCredentialOptions.SendCertificateChain` - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/Credentials/ClientCertificateCredentialOptions.cs

2024-04-24 03:16 UTC, timayabi2020 requested changes
I recommend that you add a pester test for the new parameter.

2024-04-24 06:29 UTC, nayanshah commented
I don't see any test passing a real certificate or a way to mock the authentication provider, so would be difficult to write a test for the new parameter. The parameter is forwarded to `ClientCertificateCredential` class which doesn't expose the value as a public member, so not straightforward to add a C# unit test either. 

I have updated existing pester test to include the new parameter in the appropriate parameter set. Would that be sufficient given that not much new logic is being added?

2024-04-24 11:22 UTC, merged

2024-04-24 14:42 UTC, nayanshah commented
Thank you @timayabi2020 . Do you know when is the next release scheduled for?

2024-04-25 07:41 UTC, timayabi2020 commented
@nayanshah it will be out by end of this week.